#pragma once
#include <Windows.h>

// TODO
#define GIT_VERSION_NUMBER 832
#define GIT_SHORT_HASH_A "a80e5fb"
#define GIT_SHORT_HASH_W L"a80e5fb"
#define COMPILE_DATE_A "2022-01-07 10:19"
#define COMPILE_DATE_W L"2022-01-07 10:19"
#define COMPILE_YEAR_A "2022"
#define COMPILE_YEAR_W L"2022"

#define STRA(x) #x
#define STRW(x) L#x

#define STR_HELPERA(x) STRA(x)
#define STR_HELPERW(x) STRW(x)

#define SCYLLA_HIDE_VERSION_MAJOR 1
#define SCYLLA_HIDE_VERSION_MINOR 4
#define SCYLLA_HIDE_VERSION_PATCH GIT_VERSION_NUMBER

#define SCYLLA_HIDE_NAME_A "ScyllaHide"
#define SCYLLA_HIDE_NAME_W L"ScyllaHide"

#define SCYLLA_HIDE_VERSION_STRING_A STR_HELPERA(SCYLLA_HIDE_VERSION_MAJOR) "." STR_HELPERA(SCYLLA_HIDE_VERSION_MINOR) "." STR_HELPERA(SCYLLA_HIDE_VERSION_PATCH) "-" GIT_SHORT_HASH_A
#define SCYLLA_HIDE_VERSION_STRING_W STR_HELPERW(SCYLLA_HIDE_VERSION_MAJOR) L"." STR_HELPERW(SCYLLA_HIDE_VERSION_MINOR) L"." STR_HELPERW(SCYLLA_HIDE_VERSION_PATCH) L"-" GIT_SHORT_HASH_W

namespace scl
{
    void ShowAboutBox(HWND hWnd);
}
